export const MAIN_NAV = "MAIN_NAV";
export const OTHER_NAV = "OTHER_NAV";

export const ADD_CLASS = "ADD_CLASS";
export const CLEAR_CLASS = "CLEAR_CLASS";

export const SET_BUTTON_TOGGLE = "SET_BUTTON_TOGGLE";
export const CLEAR_BUTTON_TOGGLE = "CLEAR_BUTTON_TOGGLE";

export const ADD_CURRENT_CLASS = "ADD_CURRENT_CLASS";
export const CLEAR_CURRENT_CLASS = "CLEAR_CURRENT_CLASS";

export const ADD_BILLING_INFORMATION = "ADD_BILLING_INFORMATION";
export const CLEAR_BILLING_INFORMATION = "CLEAR_BILLING_INFORMATION";

export const START_SUCCESS_MESSAGE = "START_SUCCESS_MESSAGE";
export const END_SUCCESS_MESSAGE = "END_SUCCESS_MESSAGE";

export const MOBILE_NAV_SHOW = "MOBILE_NAV_SHOW";
export const MOBILE_NAV_HIDE = "MOBILE_NAV_HIDE";
